### ISSUE TITLE
TypeError: Object #<Object> has no method 'getProfileUserInfo'

### ISSUE THREAD

**Issue by shosti** [rainforestapp/tester-chrome-extension#503]
https://sentry.io/rainforest-1/tester-chrome-extension/issues/113915325/

```
TypeError: Object #<Object> has no method 'getProfileUserInfo'
  at Object.setupChromeEvents (chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js:2536:19)
  at Object../app (chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js:2768:15)
  at s (chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js:1:254)
  at e (chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js:1:425)

TypeError: Object #<Object> has no method 'getProfileUserInfo'
```

**Comment by sweeneyapps** [comment]
I would suggest to removing "getProfileUserInfo" because it has nothing to do with identifying testers w/ RainforestQA tester account at all.  It's just chrome's (google account) login info.   I don't use the same google account for RainforestQA tester account.
