### ISSUE TITLE
TypeError Object.assign is not a function

### ISSUE THREAD

**Issue by shosti** [rainforestapp/tester-chrome-extension#626]
https://sentry.io/rainforest-1/tester-chrome-extension/issues/162663952/

```
TypeError: Object.assign is not a function
  at renderIconImage (src/chrome/renderIcon.js:41:40)
  at render (src/chrome/renderIcon.js:47:4)
  at store (src/chrome/renderIcon.js:50:2)
  at window (src/chrome/index.js:35:13)
  at window (src/bootstrap.js:13:38)
```

**Comment by shosti** [comment]
Only happened once (probably an obscure issue with the polyfill). Closing for now.
